FROM node:18.20.2-alpine3.19

WORKDIR /app

# Copy package files
COPY package*.json ./
RUN npm ci --only=production

# Copy application
COPY . .

# Build application
RUN npm run build

# Expose port
EXPOSE 3000

# Run the application
CMD ["npm", "run", "preview", "--", "--host", "0.0.0.0", "--port", "3000"]